import type { Business, Integration } from "./businesses";
import { channelCards, integrationLabels } from "./businesses";

export type ExportRange = "7d" | "1m" | "3m" | "1y";

type BriefOpts = {
  range?: ExportRange;
  generatedAt?: Date;
};

const RANGE_LABEL: Record<ExportRange, string> = {
  "7d": "Last 7 days",
  "1m": "Last 30 days",
  "3m": "Last 90 days",
  "1y": "Last 365 days",
};

const RANGE_DAYS: Record<ExportRange, number> = {
  "7d": 7,
  "1m": 30,
  "3m": 90,
  "1y": 365,
};

function fmtDate(d: Date): string {
  return d.toISOString().split("T")[0];
}

export function generateBrief(business: Business, opts: BriefOpts = {}): string {
  const range = opts.range ?? "7d";
  const generatedAt = opts.generatedAt ?? new Date();
  const days = RANGE_DAYS[range];

  const endDate = new Date(generatedAt);
  const startDate = new Date(endDate);
  startDate.setDate(startDate.getDate() - days);

  const prevEndDate = new Date(startDate);
  prevEndDate.setDate(prevEndDate.getDate() - 1);
  const prevStartDate = new Date(prevEndDate);
  prevStartDate.setDate(prevStartDate.getDate() - days + 1);

  const connected = business.integrations.map((i) => integrationLabels[i]).join(", ");
  const shortRef = business.shortName ?? business.name;

  const channelsMd = business.integrations
    .flatMap((key) => renderChannel(key))
    .join("\n");

  return [
    `# ${business.name} — Signal Brief`,
    ``,
    `*Period: ${fmtDate(startDate)} to ${fmtDate(endDate)} (${RANGE_LABEL[range]})*`,
    `*Compared to: ${fmtDate(prevStartDate)} to ${fmtDate(prevEndDate)}*`,
    `*Generated by CQ Signal on ${fmtDate(generatedAt)}*`,
    ``,
    `## Business context`,
    ``,
    `- **Name:** ${business.name}${business.shortName ? ` (${business.shortName})` : ""}`,
    `- **Vertical:** ${business.vertical}`,
    `- **Profile:** ${business.tagline}`,
    `- **Connected channels:** ${connected}`,
    ``,
    `## Channel snapshot`,
    ``,
    channelsMd,
    ``,
    `## Suggested prompts`,
    ``,
    `Copy any of these into your LLM (Claude, Gemini, ChatGPT, your own agent) to analyze this brief.`,
    ``,
    `**Top moves this period.**`,
    `> Given the brief above, what are the two or three highest-leverage actions ${shortRef} should take this week? Be specific about channel, effort, and expected impact.`,
    ``,
    `**Anomaly hunt.**`,
    `> Identify anything in the data that looks anomalous compared to the prior period. Quantify and explain.`,
    ``,
    `**Client-facing summary.**`,
    `> Write a four-sentence client-facing update for ${shortRef} based on the data. Tone: confident, direct, no jargon.`,
    ``,
    `**Budget reallocation.**`,
    `> If I can only shift budget between channels this week, which channel should get more and which should get less? Justify with the numbers.`,
    ``,
    `## Connect CQ Signal to your own agent`,
    ``,
    `Markdown is one way to pull data out. You can also wire your agent directly to Signal:`,
    ``,
    `- **REST API (preview):** \`GET /api/businesses/${business.slug}/export?format=json&range=${range}\``,
    `- **MCP server (coming):** \`https://cq-signal-app.vercel.app/mcp\` — point Claude Code or any MCP-capable agent at this URL for live tools like \`get_business_metrics\`, \`compare_periods\`, \`list_businesses\`.`,
    `- **Per-workspace API keys:** configured in Settings → Agents & AI.`,
    ``,
    `---`,
    `*CQ Signal · ${generatedAt.toISOString()}*`,
    ``,
  ].join("\n");
}

function renderChannel(key: Integration): string[] {
  const card = channelCards[key];
  if (!card) return [];
  return [
    `### ${card.label} — ${card.source}`,
    card.sourceDescription ? `*${card.sourceDescription}*` : "",
    ``,
    `- **${card.primary.label}:** ${card.primary.value} *(vs prior period: —)*`,
    ...card.secondary.map((s) => `- **${s.label}:** ${s.value} *(vs prior period: —)*`),
    ``,
    `*Live ${card.source} integration pending. Values populate once connected.*`,
    ``,
  ].filter((line, i) => !(i === 1 && line === ""));
}
