import Image from "next/image";

type Props = {
  businessName: string;
  generatedAt: string;
};

function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });
}

export function ReportFooter({ businessName, generatedAt }: Props) {
  return (
    <footer className="mt-2 rounded-xl bg-neutral-900 px-9 py-7 text-center text-sm dark:bg-neutral-950">
      <Image
        src="/cq-signal-logo-dark.png"
        alt="CQ Signal"
        width={120}
        height={28}
        className="mx-auto mb-3.5 h-7 w-auto opacity-90"
      />
      <p className="text-xs text-neutral-400">
        Report generated by{" "}
        <a
          href="https://creativequalitymarketing.com"
          target="_blank"
          rel="noopener noreferrer"
          className="font-semibold text-brand transition-colors hover:text-brand/80"
        >
          Creative Quality Marketing
        </a>
        <span className="mx-2 opacity-50">·</span>
        creativequalitymarketing.com
        <span className="mx-2 opacity-50">·</span>
        {formatDate(generatedAt)}
      </p>
      <p className="mt-3 text-[10px] uppercase tracking-wider text-neutral-500">
        Confidential — Prepared exclusively for {businessName}
      </p>
    </footer>
  );
}
